FROM node

#RUN curl -OL https://github.com/protocolbuffers/protobuf/releases/download/v28.1/protoc-28.1-linux-aarch_64.zip
#RUN unzip protoc-28.1-linux-aarch_64.zip -d protoc3
#RUN mv protoc3/bin/* /usr/local/bin/
#RUN mv protoc3/include/* /usr/local/include/


RUN wget https://github.com/scottburch/tvs/archive/refs/heads/main.zip
RUN unzip main.zip

WORKDIR tvs-main

COPY ./packages/blockchain/cometBFT/linux_arm64/cometbft /usr/local/bin
RUN yarn

WORKDIR packages/crypto
RUN yarn build

WORKDIR ../proto
RUN yarn build

WORKDIR ../blockchain
RUN yarn build

WORKDIR ../vote
RUN yarn build

WORKDIR ../vote
ENTRYPOINT yarn start-demo-server
#ENTRYPOINT cat /dev/random > /dev/null
