FROM node

RUN wget https://github.com/scottburch/tvs/archive/refs/heads/main.zip
RUN unzip main.zip

WORKDIR tvs-main

COPY ./packages/blockchain/cometBFT/linux_arm64/cometbft /usr/local/bin
RUN yarn

WORKDIR packages/crypto
RUN yarn build

WORKDIR ../proto
RUN yarn build

WORKDIR ../blockchain
RUN yarn build

WORKDIR ../vote
RUN yarn build

WORKDIR ../vote
ENTRYPOINT yarn start-demo-server
#ENTRYPOINT cat /dev/random > /dev/null
