FROM node

RUN wget https://github.com/scottburch/tvs/archive/refs/heads/main.zip
RUN unzip main.zip
WORKDIR tvs-main

RUN yarn

WORKDIR packages/crypto
RUN yarn build

WORKDIR ../proto
RUN yarn build

WORKDIR ../blockchain
RUN yarn build

WORKDIR ../vote
RUN yarn build

WORKDIR ../react
RUN yarn build

WORKDIR ../webapp
RUN yarn build

WORKDIR ../webapp
ENTRYPOINT yarn serve

