services:
  testnet-root:
    container_name: testnet-root
    network_mode: host

    build:
      context: .
      dockerfile: dockerfile-testnet-node
      args:
        - NODE_NAME=root
        - ARCH=arm64
        - API_PORT=1234

  testnet-right:
    container_name: testnet-right
    networks:
      common:

    build:
      context: .
      dockerfile: dockerfile-testnet-node
      args:
        - NODE_NAME=right
        - ARCH=arm64
        - API_PORT=1235

  testnet-left:
    container_name: testnet-left
    networks:
      common:

    build:
      context: .
      dockerfile: dockerfile-testnet-node
      args:
        - NODE_NAME=left
        - ARCH=arm64
        - API_PORT=1236

  testnet-center:
    container_name: testnet-center
    networks:
      common:

    build:
      context: .
      dockerfile: dockerfile-testnet-node
      args:
        - NODE_NAME=center
        - ARCH=arm64
        - API_PORT=1237


  webapp:
    container_name: webapp
    networks:
      common:

    ports:
      - 1515:1515
    build:
      context: .
      dockerfile: dockerfile-webapp

networks:
  common:
    driver:
      host
