services:
  root:
    container_name: testnet-root
    build:
      context: .
      dockerfile: dockerfile-testnet-node
      args:
        - NODE_NAME=root
        - ARCH=arm64
        - API_PORT=1234


  right:
    container_name: testnet-right
    build:
      context: .
      dockerfile: dockerfile-testnet-node
      args:
        - NODE_NAME=right
        - ARCH=arm64
        - API_PORT=1234


  left:
    container_name: testnet-left
    build:
      context: .
      dockerfile: dockerfile-testnet-node
      args:
        - NODE_NAME=left
        - ARCH=arm64
        - API_PORT=1234


  center:
    container_name: testnet-center
    build:
      context: .
      dockerfile: dockerfile-testnet-node
      args:
        - NODE_NAME=center
        - ARCH=arm64
        - API_PORT=1234


#  webapp:
#    container_name: webapp
#    ports:
#      - 1515:1515
#    build:
#      context: .
#      dockerfile: dockerfile-webapp

