services:
  root:
    container_name: testnet-root
    ports:
      - 1515:1515
      - 1234:1234
    build:
      context: .
      dockerfile: dockerfile-testnet-node
      args:
        - NODE_NAME=root
        - API_PORT=1234


  right:
    container_name: testnet-right
    ports:
      - 1516:1515
      - 1235:1234
    build:
      context: .
      dockerfile: dockerfile-testnet-node
      args:
        - NODE_NAME=right
        - API_PORT=1234


  left:
    container_name: testnet-left
    ports:
      - 1517:1515
      - 1236:1234
    build:
      context: .
      dockerfile: dockerfile-testnet-node
      args:
        - NODE_NAME=left
        - API_PORT=1234


  center:
    container_name: testnet-center
    ports:
      - 1518:1515
      - 1237:1234
    build:
      context: .
      dockerfile: dockerfile-testnet-node
      args:
        - NODE_NAME=center
        - API_PORT=1234


  webapp-root:
    container_name: webapp-root
    network_mode: service:root
    build:
      context: .
      dockerfile: dockerfile-webapp

  webapp-right:
    container_name: webapp-right
    network_mode: service:right
    build:
      context: .
      dockerfile: dockerfile-webapp

  webapp-left:
    container_name: webapp-left
    network_mode: service:left
    build:
      context: .
      dockerfile: dockerfile-webapp

  webapp-center:
    container_name: webapp-center
    network_mode: service:center
    build:
      context: .
      dockerfile: dockerfile-webapp
