FROM node

ARG NODE_NAME
ENV NODE_NAME $NODE_NAME

ARG ARCH
ENV ARCH $ARCH

RUN wget https://github.com/scottburch/tvs/archive/refs/heads/main.zip
RUN unzip main.zip
WORKDIR tvs-main

# install cometBFT
COPY ./cometBFT/linux_${ARCH}/cometbft /usr/local/bin

RUN yarn

WORKDIR packages/crypto
RUN yarn build

WORKDIR ../proto
RUN yarn build

WORKDIR ../blockchain
RUN yarn build

WORKDIR ../vote
RUN yarn build

WORKDIR ../vote
ENTRYPOINT yarn start-testnet-node $NODE_NAME
